### ISSUE TITLE
increasing rate limits

### ISSUE THREAD

**Issue by shinigami-kun** [ariomex/api-php#1]
Hi,

Thanks for the API. I'm trying to use Ariomex API to handle my crypto trades, but the rate limit you've specified for the API calls (for almost all endpoints specially order book API) is very low and it makes your API unusable.

Please consider providing us WebSocket API or increase API call rate limits.

Also, the order book endpoint is broken and returns an empty order book randomly.

**Comment by ariomex** [comment]
> Hi,
> 
> Thanks for the API. I'm trying to use Ariomex API to handle my crypto trades, but the rate limit you've specified for the API calls (for almost all endpoints specially order book API) is very low and it makes your API unusable.
> 
> Please consider providing us WebSocket API or increase API call rate limits.
> 
> Also, the order book endpoint is broken and returns an empty order book randomly.

the issue with empty orderbook is solved, also rate limit is 10 request per second

**Comment by shinigami-kun** [comment]
well, thanks.
